Add api integration
1gory/adidas-shop-frontend pull request #11
Opened 2017-06-07 12:49 UTC by 1gory

2017-06-07 13:21 UTC, imevro requested changes

2017-06-07 13:21 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +import get from '../../api/resources';
положи просто в api.js

2017-06-07 13:21 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +  updateProducts(data) {
императивный нейминг хуевый

2017-06-07 13:21 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +    get(props.match.url).then(data => this.updateProducts(data.items));
в компонентвиллмаунт

2017-06-07 13:21 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +  updateProducts(data) {
сразу тут же и делай лоад с сервера

2017-06-07 13:21 UTC, evgenyrodionov commented on src/Products/Show/index.jsx
> +    get(props.match.url).then((data) => {
в компонентвиллмаунт

2017-06-07 13:21 UTC, evgenyrodionov commented on src/api/resources.js
> +export default url => fetch(API_BASE_URL + url).then(response => response.json());
url? странное название функции

2017-06-11 13:02 UTC, imevro requested changes

2017-06-11 13:02 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +      const products = data.items.map((product) => {
Сделай отдельную функцию `transformInputValues`

2017-06-11 13:02 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +import getImage from '../../api/getImage';
поч эт в апи

2017-06-11 13:02 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +import get from '../../api/getResource';
для каждого метода отдельный файл будешь делать? Сделай api.js и туда положи get post put del

2017-06-13 13:08 UTC, imevro requested changes

2017-06-13 13:08 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +    // this.transformInputValues = this.transformInputValues.bind(this);
убери

2017-06-13 13:08 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +                  price={product.price / 100}
трансформинпутвельюс тебе зачем нужен бы

2017-06-13 13:08 UTC, evgenyrodionov commented on src/functions/transformInputValues.js
> +  data.items.map((product) => {
зачем ты тут работаешь с массивом

2017-06-13 13:08 UTC, evgenyrodionov commented on src/Products/Show/index.jsx
> +      this.setState(data);
тут трансформинпутвельюс не надо делать?

2017-06-13 17:25 UTC, imevro requested changes

2017-06-13 17:25 UTC, evgenyrodionov commented on src/functions/transformInputValues.js
> +import getImage from './getImage';
Этот файл не должен лежать тут, потому что он относится чисто к продуктам

2017-06-13 17:25 UTC, evgenyrodionov commented on src/Products/Show/Gallery.jsx
> +      images: props.images,
зачем? заебешься потом обновлять стейт при обновлении пропов

2017-06-13 17:25 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +    get(props.match.url).then((data) => {
используй дестракт

2017-06-13 21:17 UTC, imevro requested changes
Зачем ты убрал трансформинпутвельюс???

2017-06-13 21:37 UTC, 1gory commented on src/Products/Show/index.jsx
> +      this.setState(data);
> Зачем ты убрал трансформинпутвельюс???
Бесполезная же функция была? Перегоняет из одного объекта в другой

2017-06-14 13:19 UTC, imevro approved these changes

2017-06-14 13:20 UTC, merged